app_root: .
ignored_folders:
  - vendor
  - log
  - logs
  - assets
  - public
  - grifts
  - tmp
  - bin
  - node_modules
  - .sass-cache
included_extensions:
  - .html
  - .go
  - .env
build_path: tmp
build_delay: 150ns
binary_name: hikeshi-build
command_flags: []
enable_colors: true
log_name: buffalo
