---
development:
  dialect: postgres
  database: hikeshi_development
  user: hikeshi
  password: postgres
  host: db
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://hikeshi:postgres@db:5432/hikeshi_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://hikeshi:postgres@db:5432/hikeshi_production?sslmode=disable"}}
