version: '3'
services:

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: hikeshi_development
      POSTGRES_USER: hikeshi
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    ports:
      - 3000:3000
