version: '3'

tasks:
  default:
    cmds:
      - task: build
      - task: run

  init:
    desc: Initialize the database
    cmds:
      - task: db
      - /bin/sleep 6
      - ./bin/hikeshi migrate
      - ./bin/hikeshi task db:seed:users

  run:
    desc: Run hikeshi
    cmds:
      - ./bin/hikeshi

  dev:
    desc: Run hikeshi in developer mode
    deps: [ assets ]
    sources:
      - assets/*
      - templates/**/*.html
      - templates/*.html
      - actions/*
      - middleware/*
      - models/*
    generates:
      - tmp/hikeshi-build
    cmds:
      - go build -v -tags development -o tmp/hikeshi-build
      - ./tmp/hikeshi-build
    method: timestamp

  build:
    desc: Build hikeshi
    cmds:
      - buffalo build

  assets:
    desc: Bundle assets for building
    source:
      - assets/**/*
    generates:
      - public/assets/*.js
      - public/assets/*.css
      - packrd/packed-packr.go
    cmds:
      - webpack
      - packr2

  db:
    desc: Start a postgres database with Docker
    cmds:
      - docker run -p 1234:5432 -e POSTGRES_DB=hikeshi_development -e POSTGRES_USER=hikeshi -e POSTGRES_PASSWORD=postgres -d postgres:alpine

