version: '3'

tasks:
  default:
    cmds:
      - task: run

  run:
    desc: Build and run hikeshi
    cmds:
      - task: build
      - ./bin/hikeshi dev

  dev:
    desc: Run hikeshi in developer mode
    sources:
      - actions/*.go
      - assets/**/*.js
      - assets/**/*.scss
    cmds:
      - buffalo dev

  build:
    desc: Build hikeshi
    cmds:
      - buffalo build

  release:
    desc: Update release tags and push out new release
    cmds:
      - git tag $(svu next) -m "Latest release" $(git rev-parse --short HEAD)
      - goreleaser

  includes:
    install: ./Taskfile_{{OS}}.yml
