version: '3'

tasks:
  default:
    cmds:
      - task: build
      - task: run

  run:
    desc: Run hikeshi
    cmds:
      - ./bin/hikeshi

  build:
    desc: Build hikeshi
    cmds:
      - buffalo build

  init:
    desc: Initialize the database
    cmds:
      - task: db
      - ./bin/hikeshi migrate
      - ./bin/hikeshi task db:seed:users


  dev:
    desc: Run hikeshi in developer mode
    sources:
      - actions/*.go
      - assets/**/*.js
      - assets/**/*.scss
      - templates/*.plush.html
    generates:
      - ./a/*
      - ./tmp/*
    cmds:
      - packr2
      - buffalo dev

  db:
    desc: Start a postgres database with Docker
    cmds:
      - docker run -p 1234:5432 -e POSTGRES_DB=hikeshi_development -e POSTGRES_USER=hikeshi -e POSTGRES_PASSWORD=postgres -d postgres:alpine

