version: '3'

tasks:
  default:
    cmds:
      - task: build
      - task: run

  run:
    desc: Run hikeshi
    cmds:
      - ./bin/hikeshi

  dev:
    desc: Run hikeshi in developer mode
    sources:
      - actions/*.go
      - assets/**/*.js
      - assets/**/*.scss
    generates:
      - ./a/*
      - ./tmp/*
    cmds:
      - packr2
      - buffalo dev

  docker:
    desc: Start a postgres database with Docker
    cmds:
      - docker run -p 1234:5432 \
        -e POSTGRES_DB=hikeshi_development \
        -e POSTGRES_USER=hikeshi \
        -e POSTGRES_PASSWORD=postgres \
        -d postgres:alpine

  build:
    desc: Build hikeshi
    cmds:
      - buffalo build
